
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-15
owner: ucsb-cs156-s26
repo_name: team02-s26-15
pull_requests: [{"author":{"id":"U_kgDOCxz58A","is_bot":false,"login":"schoolKris08","name":"Kristopher Rangel-Olivos"},"headRefName":"KR-helpRequest-edit-page","number":104,"title":"Kr help request edit page","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/104"},{"author":{"id":"U_kgDOCxz58A","is_bot":false,"login":"schoolKris08","name":"Kristopher Rangel-Olivos"},"headRefName":"KR-helpRequest-IndexPage","number":96,"title":"Kr help request index page","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/96"},{"author":{"id":"U_kgDOCxz58A","is_bot":false,"login":"schoolKris08","name":"Kristopher Rangel-Olivos"},"headRefName":"KR-create-helpRequest-page","number":91,"title":"Kr create help request page","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/91"},{"author":{"id":"U_kgDOC5bJ1g","is_bot":false,"login":"katelyn-dang","name":""},"headRefName":"kd-create-review-page","number":89,"title":"kd create review page","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/89"},{"author":{"id":"U_kgDOCxz58A","is_bot":false,"login":"schoolKris08","name":"Kristopher Rangel-Olivos"},"headRefName":"KR-helpRequest-placeholder-pages","number":85,"title":"Kr help request placeholder pages","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/85"}]
