title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s26/team02-s26-15
owner: ucsb-cs156-s26
repo_name: team02-s26-15
pull_requests: [{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-ucsbdcmi-end2end-test","number":121,"title":"mf - ucsbdcmi end2end test","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/121"},{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-ucsbdcmi-integration-test","number":120,"title":"mf - ucsbdcmi integration test","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/120"},{"author":{"id":"U_kgDOC0_I2w","is_bot":false,"login":"SteveZhaoUcsb","name":"Xuanbo Zhao"},"headRefName":"xuanbo-articles-e2e-tests","number":116,"title":"Xuanbo articles e2e tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/116"},{"author":{"id":"U_kgDOC0_I2w","is_bot":false,"login":"SteveZhaoUcsb","name":"Xuanbo Zhao"},"headRefName":"xuanbo-articles-integration-test","number":115,"title":"Add ArticlesIT integration test","url":"https://github.com/ucsb-cs156-s26/team02-s26-15/pull/115"}]
